### ISSUE TITLE
Duplicated BinaryDilation interface (in morphology and nibabel)

### ISSUE THREAD

**Issue by oesteban** [nipreps/niworkflows#708]
I think the right thing to do is moving the old one (in `niworkflows.interfaces.nibabel`) into the new morphology module, leaving a shim for backwards compatibility.

WDYT?

cc/ @celprov

**Comment by effigies** [comment]
I think it makes more sense to emit a `DeprecationWarning` during `__init__` and then remove it, rather than do a shim. It doesn't do the identical thing if the input image is non-mask data. Hopefully people are only passing masks, but they should make an explicit decision to adopt the new behavior.

**Comment by effigies** [comment]
Will be deprecated in 1.7.0, to be released shortly.
