### ISSUE TITLE
[ENH] Add PET query to collect_data in utils

### ISSUE THREAD

**Issue by mnoergaard** [nipreps/niworkflows#709]
To accommodate easy retrieval of PET data to run PET workflows similar to fMRIPrep it would be useful to enhance collect_data in utils to be able to query pet data from pybids.  

The enhancement should be pretty straightforward by adding the following to queries on line 220
"pet": {"datatype": "pet", "suffix": "pet"}

**Comment by effigies** [comment]
I'm fine with this. Not sure if it makes sense to keep consolidating this across tools, since the original version came from before PyBIDS had usable queries. I might see if you can get away with writing your own query for now and see how much of the extra stuff we have in here makes sense to replicate.

**Comment by mnoergaard** [comment]
Will do - thanks @effigies.
